import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * LexiVault Database Schema
 * Optimized for:
 * 1. Hybrid Search (Vector + Full-text)
 * 2. Granular Monetization (User-level unlocks)
 * 3. High-performance Reader (Lazy-loading pages)
 */

export default defineSchema({
	// --- Core Document Metadata ---
	documents: defineTable({
		title: v.string(), // e.g., "Bank Indonesia Regulation No. 10/1998"
		description: v.optional(v.string()),
		category: v.string(), // "Banking", "Tax", "Corporate"
		year: v.number(),
		status: v.union(
			v.literal("processing"),
			v.literal("published"),
			v.literal("error"),
			v.literal("archived")
		),

		// Processing Metadata
		processingProgress: v.optional(v.number()), // 0-100%
		processingError: v.optional(v.string()),
		processedPages: v.optional(v.number()), // Count of completed pages

		// File Storage references
		storageId: v.id("_storage"), // The raw scanned PDF stored in Convex
		totalPageCount: v.number(),

		// Monetization
		isPremium: v.boolean(),
		price: v.optional(v.number()), // In IDR, e.g., 50000
	})
		.index("by_status", ["status"])
		.index("by_category", ["category"])
		.index("by_year", ["year"])
		.searchIndex("search_title", {
			searchField: "title",
			filterFields: ["category", "year"],
		}),

	// --- Processed Content (Pages/Chunks) ---
	// We break documents into pages to enable lazy-loading in TanStack Start
	documentContent: defineTable({
		documentId: v.id("documents"),
		pageNumber: v.number(),
		title: v.optional(v.string()), // Chapter/Article title found on this page
		markdown: v.string(), // The clean text from Gemini 3 Flash

		// Processing status for distributed OCR
		status: v.union(
			v.literal("pending"),
			v.literal("processing"),
			v.literal("completed"),
			v.literal("error")
		),

		// For Split View verification
		originalPageImageId: v.optional(v.id("_storage")), // Image of this specific page

		// Search Vector: Storing the embedding for semantic search
		// Used by Convex Vector Search to find relevant passages
		embedding: v.array(v.float64()),
	})
		.index("by_document_page", ["documentId", "pageNumber"])
		.index("by_document_status", ["documentId", "status"])
		.vectorIndex("by_embedding", {
			// text-embedding-004 uses 768 dimensions
			dimensions: 768,
			vectorField: "embedding",
			filterFields: ["documentId"],
		}),

	// --- Table of Contents / Index ---
	// Generated by AI to power the Sidebar (UAside/USlideover)
	documentIndex: defineTable({
		documentId: v.id("documents"),
		label: v.string(), // "Pasal 1: Ketentuan Umum"
		level: v.number(), // 1 for Chapter, 2 for Article, etc.
		targetPage: v.number(),
	}).index("by_document", ["documentId"]),

	// --- User & Access Management ---
	users: defineTable({
		tokenIdentifier: v.string(), // From Clerk (e.g., "user_2NNE...")
		email: v.string(),
		name: v.optional(v.string()),
		role: v.union(v.literal("user"), v.literal("admin")),
		credits: v.number(),
	}).index("by_token", ["tokenIdentifier"]),

	// --- Purchases & Unlocks ---
	// Tracks which user has unlocked which specific document
	unlockedDocuments: defineTable({
		userId: v.id("users"),
		documentId: v.id("documents"),
		unlockedAt: v.number(),
		amountPaid: v.number(),
	}).index("by_user_doc", ["userId", "documentId"]),
});
